package de.zeros.ones.model;

// Generated 04.09.2014 09:43:51 by Hibernate Tools 3.4.0.CR1

/**
 * Guestbook generated by hbm2java
 */
public class Guestbook implements java.io.Serializable {

	private Long id;
	private String author;
	private String comment;
	private long date;

	public Guestbook() {
	}

	public Guestbook(String author, String comment, long date) {
		this.author = author;
		this.comment = comment;
		this.date = date;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public long getDate() {
		return this.date;
	}

	public void setDate(long date) {
		this.date = date;
	}

}
